version: "3.9"

services:
  postgres:
    image: jsebas656/postgres-arepabuelas:latest
    container_name: arepabuelas-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: jsebas656/arepabuelas-backend:latest
    container_name: arepas-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_URL: "jdbc:postgresql://postgres:5432/arepabuelasdb"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "Elden_Bloodborne2PC_Souls2"
      APP_AES_KEY: "1234567890123456"

volumes:
  postgres_data:
